version: "3.8"
services:
  db:
    image: postgres:18-alpine
    container_name: ai-api-postgres
    restart: always
    environment:
      POSTGRES_DB: ai_api
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    command: >
      postgres  -c max_connections=200  -c io_method=io_uring  -c fsync=off
volumes:
  pgdata:
